# -*- coding: utf-8 -*-
"""
工作流种子数据

从内置 Python 工作流提取结构定义，用于初始化可视化编辑器。
"""

INTENT_CLASSIFIER_DEF = {
    "name": "意图分类路由工作流",
    "description": "意图分类路由：根据用户输入自动识别意图（产品咨询/订单状态/技术支持/投诉/账单）并分发处理",
    "state_schema": {
        "messages": "list",
        "intent": "str",
        "confidence": "float",
        "response": "str",
        "approved": "Optional[bool]",
        "approval_comments": "Optional[str]",
        "error": "Optional[str]",
    },
    "graph_data": {
        "entry_point": "classify",
        "nodes": [
            {
                "id": "classify",
                "type": "router",
                "label": "意图分类",
                "position": {"x": 400, "y": 50},
                "handler": "classify",
                "config": {
                    "routing_mode": "llm_or_rule",
                    "description": "LLM 意图分类 + 规则降级",
                },
            },
            {
                "id": "product_inquiry",
                "type": "processor",
                "label": "产品咨询",
                "position": {"x": 100, "y": 280},
                "handler": "product_inquiry",
                "config": {"description": "处理产品咨询"},
            },
            {
                "id": "order_status",
                "type": "processor",
                "label": "订单状态",
                "position": {"x": 260, "y": 280},
                "handler": "order_status",
                "config": {"description": "处理订单状态查询"},
            },
            {
                "id": "technical_support",
                "type": "processor",
                "label": "技术支持",
                "position": {"x": 420, "y": 280},
                "handler": "technical_support",
                "config": {"description": "处理技术支持（可能需要人工审批）"},
            },
            {
                "id": "complaint",
                "type": "processor",
                "label": "投诉处理",
                "position": {"x": 580, "y": 280},
                "handler": "complaint",
                "config": {"description": "处理投诉和反馈"},
            },
            {
                "id": "billing",
                "type": "processor",
                "label": "账单问题",
                "position": {"x": 740, "y": 280},
                "handler": "billing",
                "config": {"description": "处理账单和发票问题"},
            },
            {
                "id": "other",
                "type": "processor",
                "label": "其他",
                "position": {"x": 900, "y": 280},
                "handler": "other",
                "config": {"description": "处理闲聊或其他无法归类的问题"},
            },
        ],
        "edges": [
            {
                "id": "e-classify-product",
                "source": "classify",
                "target": "product_inquiry",
                "type": "conditional",
                "condition": {"field": "intent", "operator": "==", "value": "product_inquiry"},
            },
            {
                "id": "e-classify-order",
                "source": "classify",
                "target": "order_status",
                "type": "conditional",
                "condition": {"field": "intent", "operator": "==", "value": "order_status"},
            },
            {
                "id": "e-classify-technical",
                "source": "classify",
                "target": "technical_support",
                "type": "conditional",
                "condition": {"field": "intent", "operator": "==", "value": "technical_support"},
            },
            {
                "id": "e-classify-complaint",
                "source": "classify",
                "target": "complaint",
                "type": "conditional",
                "condition": {"field": "intent", "operator": "==", "value": "complaint"},
            },
            {
                "id": "e-classify-billing",
                "source": "classify",
                "target": "billing",
                "type": "conditional",
                "condition": {"field": "intent", "operator": "==", "value": "billing"},
            },
            {
                "id": "e-classify-other",
                "source": "classify",
                "target": "other",
                "type": "conditional",
                "condition": {"field": "intent", "operator": "==", "value": "other"},
            },
            {"id": "e-product-end", "source": "product_inquiry", "target": "__end__", "type": "normal"},
            {"id": "e-order-end", "source": "order_status", "target": "__end__", "type": "normal"},
            {"id": "e-technical-end", "source": "technical_support", "target": "__end__", "type": "normal"},
            {"id": "e-complaint-end", "source": "complaint", "target": "__end__", "type": "normal"},
            {"id": "e-billing-end", "source": "billing", "target": "__end__", "type": "normal"},
            {"id": "e-other-end", "source": "other", "target": "__end__", "type": "normal"},
        ],
    },
}

APPROVAL_DEF = {
    "name": "自动化审批工作流",
    "description": "自动化审批工作流：支持自动审批和人工审批（Human-in-the-Loop）",
    "state_schema": {
        "request": "dict",
        "approval_level": "str",
        "approval_status": "str",
        "auto_evaluation": "dict",
        "risk_level": "str",
        "recommended_action": "str",
        "approval_history": "list",
        "requires_human": "bool",
        "human_approved": "Optional[bool]",
        "human_comments": "Optional[str]",
        "approver_id": "Optional[str]",
        "final_status": "str",
        "final_decision": "str",
        "notification_sent": "bool",
        "error": "Optional[str]",
    },
    "graph_data": {
        "entry_point": "submit",
        "nodes": [
            {
                "id": "submit",
                "type": "processor",
                "label": "提交申请",
                "position": {"x": 400, "y": 50},
                "handler": "submit",
                "config": {"description": "验证请求并生成请求 ID"},
            },
            {
                "id": "evaluate",
                "type": "processor",
                "label": "自动评估",
                "position": {"x": 400, "y": 200},
                "handler": "evaluate",
                "config": {"description": "基于规则评估风险等级和推荐动作"},
            },
            {
                "id": "auto_approve",
                "type": "processor",
                "label": "自动审批",
                "position": {"x": 200, "y": 350},
                "handler": "auto_approve",
                "config": {"description": "低风险请求自动通过"},
            },
            {
                "id": "human_approval",
                "type": "router",
                "label": "人工审批",
                "position": {"x": 600, "y": 350},
                "handler": "human_approval",
                "config": {"description": "中高风险请求等待人工审批（Human-in-the-Loop）"},
            },
            {
                "id": "notify",
                "type": "processor",
                "label": "发送通知",
                "position": {"x": 400, "y": 500},
                "handler": "notify",
                "config": {"description": "发送审批结果通知"},
            },
        ],
        "edges": [
            {"id": "e-submit-evaluate", "source": "submit", "target": "evaluate", "type": "normal"},
            {
                "id": "e-evaluate-auto",
                "source": "evaluate",
                "target": "auto_approve",
                "type": "conditional",
                "condition": {"field": "recommended_action", "operator": "==", "value": "auto_approve"},
            },
            {
                "id": "e-evaluate-human",
                "source": "evaluate",
                "target": "human_approval",
                "type": "conditional",
                "condition": {"field": "recommended_action", "operator": "!=", "value": "auto_approve"},
            },
            {"id": "e-auto-notify", "source": "auto_approve", "target": "notify", "type": "normal"},
            {
                "id": "e-human-notify",
                "source": "human_approval",
                "target": "notify",
                "type": "conditional",
                "condition": {"field": "final_status", "operator": "in", "value": "approved,rejected"},
            },
            {
                "id": "e-human-end",
                "source": "human_approval",
                "target": "__end__",
                "type": "conditional",
                "condition": {"field": "final_status", "operator": "not_in", "value": "approved,rejected"},
            },
            {"id": "e-notify-end", "source": "notify", "target": "__end__", "type": "normal"},
        ],
    },
}
